#!/bin/sh
sudo -l
apt-get update
# chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb

# lantern VPN
wget https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-64-bit.deb
dpkg -i lantern-installer-beta-64-bit.deb

#multi-terminal
sudo apt-get -y install terminator

#nautilus-open-terminal
sudo apt-get -y install nautilus-open-terminal

#wine
sudo add-apt-repository -y ppa:ubuntu-wine/ppa
sudo apt-get update
sudo apt-get install -y wine1.7

#timeShift
sudo apt-add-repository -y ppa:teejee2008/ppa
sudo apt-get install timeshift
#hand set
#PS1='\[\033[1;31;1m\]\u@\h:\[\033[1;32;1m\]\w\[\033[1;33;1m\]\$\[\033[1;37;1m\]' in ～/.bashrc
#font set Ubuntu Mono 10 in ubuntu Tweak and teminor
#update GPU
